# This makefile has been generated by clice - the command line coding ecosystem
#	more details at www.benningtons.net
# built on 14042017 at 2337

# Shell command variables
SHELL = /bin/sh
GCC = /usr/bin/gcc
CFLAGS= -D$(GXT_DEBUG) -std=gnu11 -Wall -fmax-errors=5

# Install paths according to GNU make standards
prefix = /usr/local
bindir = $(prefix)/bin
includedir = $(prefix)/include
completedir = /etc/bash_completion.d
objdir = $(GXT_CODE_OBJECT)

# This project's executable programs
all:	\
	nc_example $(objdir)/libgxtnc.a 

# Tidy-up.
clean:
	-rm *~

# Install project for operational use
install:	\
	$(includedir)/nc_main.h $(bindir)/nc_example 
$(includedir)/nc_main.h: nc_main.h
	sudo cp $^ $@
$(bindir)/nc_example: nc_example
	sudo cp $^ $@

# Remove project from operational use
uninstall:
	sudo rm $(includedir)/nc_main.h
	sudo rm $(bindir)/nc_example

# Functions and their dependencies

nc_example: nc_example.c $(objdir)/libgxtnc.a $(includedir)/nc_main.h $(includedir)/ut_error.h \
	 
	$(GCC) $(CFLAGS) $^ -o $@ -lncurses -lmenu
$(objdir)/libgxtnc.a: $(objdir)/nc_input.o $(objdir)/nc_menu.o $(objdir)/nc_message.o \
	 $(objdir)/nc_start.o $(objdir)/nc_stop.o $(objdir)/nc_utils.o 
	ar rs $(objdir)/libgxtnc.a $(objdir)/nc_input.o $(objdir)/nc_menu.o $(objdir)/nc_message.o \
	 $(objdir)/nc_start.o $(objdir)/nc_stop.o $(objdir)/nc_utils.o
$(objdir)/nc_input.o: nc_input.c $(includedir)/nc_main.h $(objdir)/libgxtnc.a 
	$(GCC) $(CFLAGS) -c $< -o $@
$(objdir)/nc_menu.o: nc_menu.c $(includedir)/nc_main.h $(objdir)/libgxtnc.a $(includedir)/ut_error.h \
	 
	$(GCC) $(CFLAGS) -c $< -o $@
$(objdir)/nc_message.o: nc_message.c 
	$(GCC) $(CFLAGS) -c $< -o $@
$(objdir)/nc_start.o: nc_start.c 
	$(GCC) $(CFLAGS) -c $< -o $@
$(objdir)/nc_stop.o: nc_stop.c 
	$(GCC) $(CFLAGS) -c $< -o $@
$(objdir)/nc_utils.o: nc_utils.c $(includedir)/nc_main.h 
	$(GCC) $(CFLAGS) -c $< -o $@
